---
# handlers file for src/roles/httpd
- name: Restart httpd
  become: true
  service:
    name: httpd
    state: restarted

- name: Restart firewalld
  become: true
  systemd:
    state: restarted
    name: firewalld
    enabled: true
